name: domain  Scanner

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain to scan manually'
        required: true
        default: 'example.com'
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 6 AM UTC

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Tools
        run: |
          # Install subfinder
          go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          
          # Install nuclei
          go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
          
          # Install assetfinder
          go install -v github.com/tomnomnom/assetfinder@latest
          
          # Install jq for JSON processing
          sudo apt-get update && sudo apt-get install -y jq

      - name: Validate Secrets
        run: |
          if [ -z "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            echo "::error::DISCORD_WEBHOOK secret is not set"
            exit 1
          fi
          echo "DISCORD_WEBHOOK=${{ secrets.DISCORD_WEBHOOK }}" >> $GITHUB_ENV

      - name: Set Domain
        id: set_domain
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "DOMAIN=${{ github.event.inputs.domain }}" >> $GITHUB_ENV
          else
            echo "DOMAIN=example.com" >> $GITHUB_ENV
          fi

      - name: Notify Start
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "content": "🔍 **Scan Started**\n**Domain:** ${{ env.DOMAIN }}\n**Trigger:** ${{ github.event_name }}\n**Tools:** Subfinder + Assetfinder + Nuclei"
          }' "${{ env.DISCORD_WEBHOOK }}"

      - name: Run Subfinder
        run: |
          subfinder -d ${{ env.DOMAIN }} -silent -o subfinder-subs.txt
          echo "SUBFINDER_SUBS_FOUND=$(wc -l < subfinder-subs.txt)" >> $GITHUB_ENV

      - name: Run Assetfinder
        run: |
          assetfinder -subs-only ${{ env.DOMAIN }} > assetfinder-subs.txt
          echo "ASSETFINDER_SUBS_FOUND=$(wc -l < assetfinder-subs.txt)" >> $GITHUB_ENV

      - name: Combine All Subdomains
        run: |
          cat subfinder-subs.txt assetfinder-subs.txt | sort -u > subdomains.txt
          echo "TOTAL_SUBDOMAINS_FOUND=$(wc -l < subdomains.txt)" >> $GITHUB_ENV

      - name: Notify Subdomain Results
        run: |
          SUBDOMAINS_CONTENT=$(cat subdomains.txt)
          MESSAGE="✅ **Subdomain Discovery Complete**\n**Domain:** ${{ env.DOMAIN }}\n**Subfinder:** ${{ env.SUBFINDER_SUBS_FOUND }}\n**Assetfinder:** ${{ env.ASSETFINDER_SUBS_FOUND }}\n**Total:** ${{ env.TOTAL_SUBDOMAINS_FOUND }}\n\n\`\`\`\n$SUBDOMAINS_CONTENT\n\`\`\`"
          
          if [ ${#MESSAGE} -gt 1900 ]; then
            TRUNCATED=$(echo "$SUBDOMAINS_CONTENT" | head -c 1800)
            MESSAGE="✅ **Subdomain Discovery Complete**\n**Domain:** ${{ env.DOMAIN }}\n**Subfinder:** ${{ env.SUBFINDER_SUBS_FOUND }}\n**Assetfinder:** ${{ env.ASSETFINDER_SUBS_FOUND }}\n**Total:** ${{ env.TOTAL_SUBDOMAINS_FOUND }}\n\n\`\`\`\n$TRUNCATED... [truncated]\n\`\`\`"
          fi
          
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\": $(echo "$MESSAGE" | jq -Rs .)}" \
            "${{ env.DISCORD_WEBHOOK }}"

      - name: Run Nuclei
        run: |
          nuclei -l subdomains.txt -severity critical,high,medium -silent -o nuclei-results.txt
          echo "NUCLEI_VULNS_FOUND=$(wc -l < nuclei-results.txt)" >> $GITHUB_ENV

      - name: Notify Vulnerability Summary
        run: |
          if [ ${{ env.NUCLEI_VULNS_FOUND }} -gt 0 ]; then
            curl -X POST -H "Content-Type: application/json" -d "{
              \"content\": \"🚨 **Vulnerabilities Found!**\n**Domain:** ${{ env.DOMAIN }}\n**Nuclei Vulnerabilities:** ${{ env.NUCLEI_VULNS_FOUND }}\"
            }" "${{ env.DISCORD_WEBHOOK }}"
          else
            curl -X POST -H "Content-Type: application/json" -d '{
              "content": "✅ **Scan Complete**\n**Domain:** ${{ env.DOMAIN }}\nNo critical/high/medium vulnerabilities found"
            }' "${{ env.DISCORD_WEBHOOK }}"
          fi

      - name: Send Nuclei Vulnerabilities
        if: env.NUCLEI_VULNS_FOUND > 0
        run: |
          while IFS= read -r vuln; do
            VULN_NAME=$(echo "$vuln" | grep -oP '\[\K[^\]]+' | head -1)
            SEVERITY=$(echo "$vuln" | grep -oP '\]\[\K[^\]]+' | head -1)
            URL=$(echo "$vuln" | grep -oP 'http[^\s]+' | head -1)
            [ -z "$VULN_NAME" ] && VULN_NAME="Unknown"
            [ -z "$SEVERITY" ] && SEVERITY="Unknown"
            
            MESSAGE="🚨 **Nuclei Vulnerability Found**\n**Domain:** ${{ env.DOMAIN }}\n**URL:** $URL\n**Vulnerability:** $VULN_NAME\n**Severity:** $SEVERITY\n\`\`\`\n$vuln\n\`\`\`"
            
            curl -X POST -H "Content-Type: application/json" \
              -d "{\"content\": $(echo "$MESSAGE" | jq -Rs .)}" \
              "${{ env.DISCORD_WEBHOOK }}"
            sleep 1
          done < nuclei-results.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scan-results
          path: |
            subfinder-subs.txt
            assetfinder-subs.txt
            subdomains.txt
            nuclei-results.txt
