name: DOMAIN SCANNER

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'ุงุชุฑู ุงููููุฉ ุงูุงูุชุฑุงุถูุฉ ูุงุณุชุฎุฏุงู ุงูุณููุฑุชุ ุฃู ุฃุฏุฎู ุฏููููุงุช ุฌุฏูุฏุฉ ููุง (ููุตููุฉ ุจูุณุงูุฉ)'
        required: true
        # ูููุฉ ุงูุชุฑุงุถูุฉ ุซุงุจุชุฉ ูุขููุฉ ูุชุฌูุจ ุฃุฎุทุงุก ุงูุชุญููู
        default: 'ุงุณุชุฎุฏู ุงูุฃูุฏุงู ูู ุงูุณููุฑุช'
  schedule:
    # ูู ููู ุงุซููู ุงูุณุงุนุฉ 6 ุตุจุงุญูุง ุจุชูููุช UTC
    - cron: '0 6 * * 1'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      domains: ${{ steps.set-domains.outputs.domains }}
    steps:
      - name: ุชุฌููุฒ ูุงุฆูุฉ ุงูุฏููููุงุช
        id: set-domains
        run: |
          # ูุฐุง ูู ุงููุต ุงูุจุฏูู ูู ุญูู ุงูุฅุฏุฎุงู "ุงูุงูุชุฑุงุถู"
          PLACEHOLDER='ุงุณุชุฎุฏู ุงูุฃูุฏุงู ูู ุงูุณููุฑุช'

          # ููุทู ูุชุญุฏูุฏ ูุงุฆูุฉ ุงูุฏููููุงุช ุงูุชู ุณูุชู ุงุณุชุฎุฏุงููุง
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # ููุชุดุบูู ุงููุฏููุ ุชุญูู ููุง ุฅุฐุง ูุงู ุงููุณุชุฎุฏู ุจุชุบููุฑ ุงููุต ุงูุจุฏูู
            if [ "${{ github.event.inputs.domain }}" != "$PLACEHOLDER" ]; then
              # ุฅุฐุง ูุงู ุจุชุบููุฑูุ ุงุณุชุฎุฏู ูุฏุฎูุงุชู ุงูุฌุฏูุฏุฉ
              domains_string="${{ github.event.inputs.domain }}"
              echo "ุงุณุชุฎุฏุงู ุงูุฏููููุงุช ุงูุชู ุฃุฏุฎููุง ุงููุณุชุฎุฏู."
            else
              # ุฅุฐุง ุชุฑู ุงููุต ุงูุจุฏููุ ุงุฑุฌุน ุฅูู ุงูุณููุฑุช
              domains_string="${{ secrets.SCAN_TARGETS }}"
              echo "ุชู ุชุฑู ุงููููุฉ ุงูุงูุชุฑุงุถูุฉุ ุณูุชู ุงุณุชุฎุฏุงู ุงูุณููุฑุช SCAN_TARGETS."
            fi
          else
            # ููุชุดุบูู ุงููุฌุฏููุ ุงุณุชุฎุฏู ุงูุณููุฑุช ุฏุงุฆููุง
            domains_string="${{ secrets.SCAN_TARGETS }}"
            echo "ุงุณุชุฎุฏุงู ุงูุณููุฑุช SCAN_TARGETS ููุชุดุบูู ุงููุฌุฏูู."
          fi

          # ุชุญูู ููุงุฆู ููุชุฃูุฏ ูู ุฃู ูุงุฆูุฉ ุงูุฏููููุงุช ููุณุช ูุงุฑุบุฉ
          if [ -z "$domains_string" ]; then
            echo "::error::ูุงุฆูุฉ ุงูุฏููููุงุช ูุงุฑุบุฉ. ุชุญูู ูู ูุฏุฎูุงุชู ุฃู ุงูุณููุฑุช SCAN_TARGETS."
            exit 1
          fi

          #
          # !!! THIS IS THE 1st MODIFIED LINE !!!
          # (ุชุญููู ุงูุณูุณูุฉ ุงููุตูุฉ ูุน ููุชุฑุฉ ุงููุฑุงุบุงุช)
          json_array=$(echo "$domains_string" | jq -R 'split(" ") | map(select(. != ""))' | jq -c .)
          #
          #
          
          echo "domains=$json_array" >> $GITHUB_OUTPUT

  scan:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        domain: ${{ fromJson(needs.setup.outputs.domains) }}

    steps:
      - name: ุงุณุชูุณุงุฎ ุงูุฑูุจู
        uses: actions/checkout@v4

      - name: ุชุซุจูุช Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: ุชุซุจูุช Nuclei
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y jq git
          echo "GOBIN=$HOME/go/bin" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/go/bin" >> $GITHUB_ENV
          go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest || true

      - name: ุงูุชุญูู ูู ุณููุฑุช ุฏูุณููุฑุฏ
        run: |
          if [ -z "${{ secrets.DISCORD_GHOST2 }}" ]; then
            echo "::error::ุงูุณููุฑุช DISCORD_GHOST2 ุบูุฑ ููุฌูุฏ."
            exit 1
          fi
          echo "DISCORD_WEBHOOK=${{ secrets.DISCORD_GHOST2 }}" >> $GITHUB_ENV

      - name: ุฅุดุนุงุฑ ุจุฏุก ุงููุญุต ูู ${{ matrix.domain }}
        run: |
          curl -s -X POST -H "Content-Type: application/json" -d "{
            \"content\": \"๐ **ุจุฏุก ูุญุต ุงูุซุบุฑุงุช ุงููุจุงุดุฑ**\n**ุงูุฏูููู:** `${{ matrix.domain }}`\n**ููุน ุงูุชุดุบูู:** `${{ github.event_name }}`\"
          }" "${{ env.DISCORD_WEBHOOK }}" || true

      - name: ุชุดุบูู ูุญุต Nuclei ุนูู ${{ matrix.domain }}
        run: |
          nuclei -u ${{ matrix.domain }} -severity critical,high,medium -silent -o nuclei-results.txt || true
          [ -f nuclei-results.txt ] || touch nuclei-results.txt
          echo "NUCLEI_VULNS_FOUND=$(wc -l < nuclei-results.txt)" >> $GITHUB_ENV

      #
      # !!! THIS IS THE 2nd MODIFIED STEP !!!
      # (ุชู ุชุนุฏูู ุงูุฎุทูุฉ ุฏู ุนุดุงู ุชูุฑุฃ ุงููุชุบูุฑ ุตุญ)
      #
      - name: ุฅุดุนุงุฑ ุจููุฎุต ุงูุซุบุฑุงุช ูู ${{ matrix.domain }}
        run: |
          # ูุฑุงุกุฉ ุงููุชุบูุฑ ูู ุงูู Environment ุงูุฎุงุต ุจุงูู Workflow
          NUCLEI_VULNS_COUNT="${{ env.NUCLEI_VULNS_FOUND }}"
          
          if [ "$NUCLEI_VULNS_COUNT" -gt 0 ]; then
            MESSAGE="๐จ **ุชู ุงูุนุซูุฑ ุนูู ุซุบุฑุงุช!**\n**ุงูุฏูููู:** ${{ matrix.domain }}\n**ุงูุนุฏุฏ ุงูุฅุฌูุงูู:** $NUCLEI_VULNS_COUNT\n\nุฌุงุฑู ุฅุฑุณุงู ุงูุชูุงุตูู..."
          else
            MESSAGE="โ **ุงูุชูู ุงููุญุต**\n**ุงูุฏูููู:** ${{ matrix.domain }}\nูู ูุชู ุงูุนุซูุฑ ุนูู ุซุบุฑุงุช."
          fi
          curl -s -X POST -H "Content-Type: application/json" -d "{\"content\": \"$MESSAGE\"}" "${{ env.DISCORD_WEBHOOK }}" || true

      - name: ุฅุฑุณุงู ุชูุงุตูู ุซุบุฑุงุช Nuclei ูู ${{ matrix.domain }}
        # ุงูุฎุทูุฉ ุฏู ูุงูุช ุณูููุฉ ูุจุชุณุชุฎุฏู ุงููุชุบูุฑ ุตุญ
        if: env.NUCLEI_VULNS_FOUND != '0'
        run: |
          while IFS= read -r vuln; do
            MESSAGE="๐จ **ุชูุงุตูู ุซุบุฑุฉ**\n**ุงูุฏูููู:** ${{ matrix.domain }}\n\`\`\`\n$vuln\n\`\`\`"
            curl -s -X POST -H "Content-Type: application/json" -d "{\"content\": $(echo "$MESSAGE" | jq -Rs .)}" "${{ env.DISCORD_WEBHOOK }}" || true
            sleep 1
          done < nuclei-results.txt

      - name: ุฑูุน ูุชุงุฆุฌ ุงููุญุต ูู ${{ matrix.domain }}
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-results-${{ matrix.domain }}
          path: nuclei-results.txt
